version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn install
artifacts:
  files:
    - target/cicd-web-project.war
    - appspec.yml
    - scripts/**/*
  discard-paths: no
